In [1]:
import pandas as pd
import numpy as np
from scipy import sparse

from sklearn.preprocessing import normalize


In [2]:
interactions_df = pd.read_csv("lastfm_user_scrobbles.csv")
titles_df=pd.read_csv("lastfm_artist_list.csv")

In [3]:
interactions_df

user_id  artist_id  scrobbles
0            1       4562      13883
1            1      10191      11690
2            1        494      11351
3            1       6673      10300
4            1       8402       8983
...        ...        ...        ...
92787     1892      10098        278
92788     1892       8660        263
92789     1892       3274        258
92790     1892       4240        232
92791     1892      10842        228

[92792 rows x 3 columns]

In [4]:
titles_df

artist_id   artist_name
0              1       __Max__
1              2       _Algol_
2              3     -123 Min.
3              4          -Oz-
4              5  -T De Sangre
...          ...           ...
17488      17489          鷺巣詩郎
17489      17490           黃立行
17490      17491           黄义达
17491      17492         黒木メイサ
17492      17493            鼓童

[17493 rows x 2 columns]

In [5]:
interactions_df.groupby('user_id').count().mean()

artist_id    49.044397
scrobbles    49.044397
dtype: float64

In [6]:
titles_df.index = titles_df['artist_id']

In [22]:
titles_dict = titles_df['artist_name'].to_dict()

In [8]:
rows, r_pos = np.unique(interactions_df.values[:, 0], return_inverse=True)

In [9]:
rows

array([   1,    2,    3, ..., 1890, 1891, 1892])

In [10]:
r_pos

array([   0,    0,    0, ..., 1891, 1891, 1891])

In [11]:
cols, c_pos = np.unique(interactions_df.values[:, 1], return_inverse=True)

In [12]:
cols

array([    1,     2,     3, ..., 17491, 17492, 17493])

In [13]:
c_pos

array([ 4561, 10190,   493, ...,  3273,  4239, 10841])

In [14]:
interactions_sparse = sparse.csr_matrix((interactions_df.values[:, 2], (r_pos, c_pos)))

In [15]:
interactions_sparse

<1892x17493 sparse matrix of type '<class 'numpy.int64'>'
	with 92723 stored elements in Compressed Sparse Row format>

In [16]:
Pui = normalize(interactions_sparse, norm ='l2', axis = 1)
sim = Pui.T*Pui
##матрицца смежности графа

In [23]:
[titles_dict[i+1] for i in sim[10734].toarray().argsort()[0][-20:]]

['The Doors',
 'Pink Floyd',
 'Joy Division',
 'Depeche Mode',
 'Marilyn Manson',
 'Paramore',
 'System Of A Down',
 'Arctic Monkeys',
 'Pearl Jam',
 'Green Day',
 'Foo Fighters',
 'Muse',
 'Alice In Chains',
 'Red Hot Chili Peppers',
 'Placebo',
 'The Smashing Pumpkins',
 'Metallica',
 'Radiohead',
 'The Beatles',
 'Nirvana']

In [26]:
[titles_dict[i+1] for i in sim[17181].toarray().argsort()[0][-20:]]

['Сергей Лазарев',
 'Gato Idiota',
 'Umaturman',
 'R.E.M.',
 'Линда',
 'Pereza',
 'The Pigeon Detectives',
 'Kings Of Convenience',
 'Глюкоза',
 'Phoenix',
 'The Redwalls',
 'Ранетки',
 'Валерий Меладзе',
 'Regina Spektor',
 'Brainstorm',
 'Hellogoodbye',
 'Sertse',
 'Gipsy Kings',
 'Zемфира',
 'Dido']

In [27]:
[titles_dict[i+1] for i in sim[17121].toarray().argsort()[0][-20:]]

['Red Hot Chili Peppers',
 'Björk',
 'Aoki Takamasa',
 'The Dillinger Escape Plan',
 'Deftones',
 'B. Fleischmann',
 '2h Company',
 'Самое Большое Простое Число',
 'Amon Tobin',
 'Devildriver',
 'Autechre',
 'Orbital',
 'Cujo',
 'Proem',
 'Ochre',
 'Massive Attack',
 'The Cinematic Orchestra',
 'Red Snapper',
 'Apparat',
 'Aphex Twin']

In [28]:
[titles_dict[i+1] for i in sim[17122].toarray().argsort()[0][-20:]]

['Amerie',
 'The Pussycat Dolls',
 'Ciara',
 'Beyonce',
 'Electrik Red',
 'Mariah Carey',
 'Kylie Minogue',
 'Lady Gaga',
 'Madonna',
 'Дантес&Олейник',
 'Janet Jackson',
 'Павел Зибров',
 'Потап И Настя',
 'Real O',
 'Наталья Могилевская',
 'Макс Барских',
 'Алина Гросу',
 'Пара Нормальных',
 'Маша Фокина',
 'Светлана Лобода']

In [29]:
[titles_dict[i+1] for i in sim[16929].toarray().argsort()[0][-20:]]

['Blood Stain Child',
 'Blink-182',
 'Фантастика',
 'Anti-Flag',
 'The Unseen',
 'Стингер',
 '40 Градусов',
 'Пурген',
 'Газон',
 'Блондинка Ксю',
 'Torment Day',
 'Enter Shikari',
 'Адаптация Пчёл',
 'Свиньи В Космосе',
 'Кожаный Олень',
 'Otep',
 'Skindred',
 '40 Укв',
 'Rammstein',
 'Rise Against']

In [30]:
interactions_sparse_transposed = interactions_sparse.transpose(copy = True)
Piu = normalize(interactions_sparse_transposed, norm = 'l2', axis = 1)
fit = Pui*Piu*Pui

In [31]:
fit

<1892x17493 sparse matrix of type '<class 'numpy.float64'>'
	with 18946119 stored elements in Compressed Sparse Row format>

In [37]:
init_set=set([titles_dict[i+1] for i in np.nonzero(interactions_sparse[520])[1].tolist()])

In [36]:
pred_set=set([titles_dict[i+1] for i in fit[520].toarray().argsort()[0][-70:].tolist()])

In [38]:
pred_set-init_set

{'30 Seconds To Mars',
 'Britney Spears',
 'Christina Aguilera',
 'Coldplay',
 'David Bowie',
 'Duran Duran',
 'Evanescence',
 'Flyleaf',
 'Him',
 'Iron Maiden',
 'Joy Division',
 'Kings Of Leon',
 'Lady Gaga',
 'Linkin Park',
 'Madonna',
 'Marilyn Manson',
 'Metallica',
 'Muse',
 'Nightwish',
 'Nine Inch Nails',
 'Oasis',
 'Opeth',
 'Pink Floyd',
 'Porcupine Tree',
 'Radiohead',
 'Rammstein',
 'System Of A Down',
 'The Beatles',
 'The Killers',
 'The Smashing Pumpkins',
 'The Smiths',
 'U2'}

In [39]:
len(pred_set-init_set)

32